#!/usr/bin/env python3
"""Generate the owl teacher SVG icon for the Python Exercises button.

Usage:
    python3 gen-owl-teacher-svg.py > ../../img/owl_teacher_python.svg
    # or regenerate in-place:
    python3 gen-owl-teacher-svg.py

Output: Page/img/owl_teacher_python.svg

Design notes:
  - 120x120 viewBox, all elements fully contained
  - Transparent background (works on any dark page)
  - Owl centered at x=60
  - Blackboard top-left corner with Python list-comprehension code
  - Gruvbox dark colour palette
  - Bright gold glasses + graduation cap for "teacher" identity
  - Designed for 80px display size; text on blackboard readable at that size
"""

import pathlib, sys, textwrap

# ── Colour palette (Gruvbox dark) ────────────────────────────────────────────
BG        = "#1d2021"   # blackboard fill
BOARD_FG  = "#8ec07c"   # blackboard border (bright aqua)
CODE_Y    = "#b8bb26"   # bright green  – keyword colour
CODE_B    = "#83a598"   # bright blue   – variable colour
CODE_P    = "#d3869b"   # bright purple – string colour
STICK_FG  = "#ebdbb2"   # light0 – pointer stick
TIP       = "#fb4934"   # bright red    – pointer tip
CAP       = "#282828"   # dark0         – graduation cap
CAP_BRIM  = "#1d2021"
TASSEL    = "#fabd2f"   # bright yellow – tassel
OWL_BODY  = "#a89984"   # light4        – body feathers
OWL_HEAD  = "#bdae93"   # light3        – head
OWL_LIGHT = "#d5c4a1"   # light2        – ear tufts / belly
EYE_WHITE = "#fbf1c7"   # light0_hard   – eye whites
EYE_DARK  = "#1d2021"   # pupil
GLASSES   = "#fabd2f"   # bright yellow – glasses frames
BEAK      = "#fe8019"   # bright orange – beak / feet
WING      = "#7c6f64"   # dark4         – wings / belly marks
BELLY     = "#d5c4a1"   # light2


def svg() -> str:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<svg xmlns="http://www.w3.org/2000/svg"',
        '     viewBox="0 0 120 120" width="120" height="120">',
        '',
        '  <!-- Generated by script/ai/gen-owl-teacher-svg.py -->',
        '  <!-- Transparent background — works on any dark page -->',
        '',
        '  <!-- ── Blackboard ── -->',
        f'  <rect x="2" y="2" width="52" height="36" rx="4"',
        f'        fill="{BG}" stroke="{BOARD_FG}" stroke-width="2.5"/>',
        f'  <text x="7" y="16" font-family="monospace" font-size="8"',
        f'        font-weight="bold" fill="{CODE_Y}">[x**2</text>',
        f'  <text x="7" y="27" font-family="monospace" font-size="8"',
        f'        font-weight="bold" fill="{CODE_B}">for x in</text>',
        f'  <text x="7" y="37" font-family="monospace" font-size="8"',
        f'        font-weight="bold" fill="{CODE_P}">range(10)]</text>',
        '',
        '  <!-- ── Pointer stick ── -->',
        f'  <line x1="44" y1="36" x2="44" y2="58"',
        f'        stroke="{STICK_FG}" stroke-width="2.5" stroke-linecap="round"/>',
        f'  <circle cx="44" cy="36" r="3" fill="{TIP}"/>',
        '',
        '  <!-- ── Owl body (centered x=60) ── -->',
        f'  <ellipse cx="60" cy="90" rx="26" ry="28" fill="{OWL_BODY}"/>',
        '',
        '  <!-- ── Owl head ── -->',
        f'  <circle cx="60" cy="62" r="22" fill="{OWL_HEAD}"/>',
        '',
        '  <!-- ── Ear tufts ── -->',
        f'  <polygon points="44,46 38,33 49,44" fill="{OWL_LIGHT}"/>',
        f'  <polygon points="76,46 82,33 71,44" fill="{OWL_LIGHT}"/>',
        '',
        '  <!-- ── Graduation cap ── -->',
        f'  <polygon points="60,34 40,46 80,46" fill="{CAP}"/>',
        f'  <rect x="42" y="46" width="36" height="5" rx="1" fill="{CAP_BRIM}"/>',
        f'  <line x1="73" y1="46" x2="79" y2="56"',
        f'        stroke="{TASSEL}" stroke-width="1.5"/>',
        f'  <circle cx="79" cy="57" r="2.5" fill="{TASSEL}"/>',
        '',
        '  <!-- ── Eyes ── -->',
        f'  <circle cx="52" cy="61" r="9"  fill="{EYE_WHITE}"/>',
        f'  <circle cx="68" cy="61" r="9"  fill="{EYE_WHITE}"/>',
        f'  <circle cx="53" cy="62" r="5"  fill="{EYE_DARK}"/>',
        f'  <circle cx="69" cy="62" r="5"  fill="{EYE_DARK}"/>',
        f'  <circle cx="55" cy="60" r="2"  fill="#fff"/>',
        f'  <circle cx="71" cy="60" r="2"  fill="#fff"/>',
        '',
        '  <!-- ── Glasses (gold) ── -->',
        f'  <circle cx="52" cy="61" r="10" fill="none"',
        f'          stroke="{GLASSES}" stroke-width="2"/>',
        f'  <circle cx="68" cy="61" r="10" fill="none"',
        f'          stroke="{GLASSES}" stroke-width="2"/>',
        f'  <!-- bridge -->',
        f'  <line x1="62" y1="61" x2="58" y2="61"',
        f'        stroke="{GLASSES}" stroke-width="2"/>',
        f'  <!-- arms -->',
        f'  <line x1="42" y1="59" x2="37" y2="56"',
        f'        stroke="{GLASSES}" stroke-width="1.8"/>',
        f'  <line x1="78" y1="59" x2="83" y2="56"',
        f'        stroke="{GLASSES}" stroke-width="1.8"/>',
        '',
        '  <!-- ── Beak ── -->',
        f'  <polygon points="60,70 56,77 64,77" fill="{BEAK}"/>',
        '',
        '  <!-- ── Belly ── -->',
        f'  <ellipse cx="60" cy="93" rx="14" ry="20" fill="{BELLY}"/>',
        f'  <path d="M55,85 l3,3 l3,-3" fill="none"',
        f'        stroke="{WING}" stroke-width="1.5"/>',
        f'  <path d="M62,85 l3,3 l3,-3" fill="none"',
        f'        stroke="{WING}" stroke-width="1.5"/>',
        f'  <path d="M55,93 l3,3 l3,-3" fill="none"',
        f'        stroke="{WING}" stroke-width="1.5"/>',
        f'  <path d="M62,93 l3,3 l3,-3" fill="none"',
        f'        stroke="{WING}" stroke-width="1.5"/>',
        '',
        '  <!-- ── Wings ── -->',
        f'  <ellipse cx="36" cy="84" rx="8" ry="18" fill="{WING}"',
        f'           transform="rotate(10 36 84)"/>',
        f'  <ellipse cx="84" cy="84" rx="8" ry="18" fill="{WING}"',
        f'           transform="rotate(-10 84 84)"/>',
        '',
        '  <!-- ── Feet ── -->',
        f'  <ellipse cx="52" cy="116" rx="8" ry="4" fill="{BEAK}"/>',
        f'  <ellipse cx="68" cy="116" rx="8" ry="4" fill="{BEAK}"/>',
        '',
        '</svg>',
    ]
    return '\n'.join(lines)


def main():
    content = svg()

    # Default output: ../../img/owl_teacher_python.svg relative to this script
    script_dir = pathlib.Path(__file__).parent
    out_path = (script_dir / '../../img/owl_teacher_python.svg').resolve()

    if len(sys.argv) > 1:
        out_path = pathlib.Path(sys.argv[1]).resolve()

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding='utf-8')
    print(f'Written: {out_path}', file=sys.stderr)

    # Also print to stdout so it can be piped
    print(content)


if __name__ == '__main__':
    main()
